docs/index.md, docs/packages/pycco.css, docs/packages/validators.html, schemas/validators.py
=> Implementation of issue #22

.coveragerc, Makefile, schemas/.coverage, schemas/.coveragerc, schemas/validators.py, schemas/validators_test.py
Unit tests for numeric validators
=> Unit tests for numeric validators

schemas/validators.py
=> Provide SHA224 validator

schemas/validators.py
=> Provide SHA384 validator

schemas/validators.py
=> Provide SHA512 validator

schemas/validators_test.py, tools/gen_sha224_sum.py
=> Unit tests for sha224 validator

schemas/validators_test.py, tools/gen_sha256_sum.py
=> Unit tests for sha256 validator

schemas/validators_test.py, tools/gen_sha384_sum.py
=> Unit tests for sha384 validator

schemas/validators_test.py, tools/gen_sha512_sum.py
=> Unit tests for sha512 validator

schemas/validators_test.py, tools/gen_md5_sum.py
=> MD5 validator

schemas/validators_test.py, tools/gen_uuid.py
=> UUID unit tests

schemas/validators_test.py, tools/gen_timestamps.py
=> Unit test for timestamp validator

schemas/validators_test.py, tools/gen_timestamps_ms.py
=> Unit test for timestamp validator ms

schemas/validators_test.py
=> Unit tests for AWS URL validator

schemas/validators_test.py
Check for incorrect type in all string validators
=> Check for incorrect type in all string validators

schemas/validators_test.py
Check for incorrect type in all hash validators
=> Check for incorrect type in all hash validators

schemas/validators_test.py
Check for incorrect type in all timestamps validators
=> Check for incorrect type in all timestamps validators

schemas/validators_test.py, tools/gen_base64.py
=> Unit test for BASE64-encoded JSON data

schemas/validators.py, schemas/validators_test.py, tools/gen_sha3_224_sum.py
=> Validator for SHA-3 224

schemas/validators.py, schemas/validators_test.py, tools/gen_sha3_256_sum.py
=> Validator for SHA-3 256

schemas/validators.py, schemas/validators_test.py
=> Validator for s 384

schemas/validators.py, schemas/validators_test.py
=> Validator for SHA-3 512

tools/gen_sha3_384_sum.py
Generator for SHA-3 384 bit hash
=> Generator for SHA-3 384 bit hash

schemas/validators.py, schemas/validators_test.py, tools/gen_blake2.py
=> BLAKE2 hash validator

schemas/validators.py, schemas/validators_test.py, tools/gen_shake_128_sum.py
=> Shake128 validator

schemas/validators.py, schemas/validators_test.py, tools/gen_shake_256_sum.py
=> Shake256 validator

Makefile, docs/index.md, docs/packages/validators.html, docs/validators.md
=> Documentation for all validators (predicates)

schemas/ccx_ocp_results.py, schemas/platform_upload_buckit_messages_test.py, schemas/validators.py, schemas/validators_test.py
=> Schema for ccx.ocp.results

docs/internal-pipeline/parquet_thanos.md
update parquet-factory Thanos part with additional information and examples
=> update parquet-factory Thanos part

setup.py
Setup.py file is added to allow installation of insights-data-schema as any regular Python package.
=> Add setup.py to simplify package installation

docs/external-pipeline/content_service.md
Adds new field to the RuleErrorKeyContent
=> update rule content schema

docs/internal-pipeline/features_service_messages.md, docs/internal-pipeline/parquet_features.md, docs/internal-pipeline/parquet_output.md, schemas/parquet_output_cluster_info.py, schemas/parquet_output_cluster_info_test.py
Reference: https://issues.redhat.com/browse/CCXDEV-6556
=> Add network kind,size and host prefix to cluster_info parquet file

docs/packages/parquet_output_alerts.html, docs/packages/parquet_output_alerts_test.html
Literate doc for output alerts
=> Literate doc for output alerts

setup.py
`Setup.py` reformatted by Black
=> `Setup.py` reformatted by Black

schemas/ccx_ocp_results.py, schemas/parquet_input_features.py, schemas/parquet_input_rule_hits.py, schemas/parquet_output_alerts.py, schemas/parquet_output_available_updates.py, schemas/parquet_output_available_updates_test.py, schemas/parquet_output_cluster_info.py, schemas/parquet_output_cluster_info_test.py, schemas/parquet_output_conditional_update_conditions.py, schemas/parquet_output_conditional_update_conditions_tests.py, schemas/parquet_output_conditional_update_risks.py, schemas/parquet_output_conditional_update_risks_test.py, schemas/parquet_output_operator_condition.py, schemas/parquet_output_rule_hits.py, schemas/platform_upload_announce_messages.py, schemas/sqs_messages.py, schemas/validators.py
Minor refactoring
- mostly unused imports has been deleted
- dead code has been eliminated
- proper type checks
=> Minor refactoring

schemas/ccx_ocp_results.py, schemas/common_test.py, schemas/parquet_input_features.py, schemas/parquet_input_rule_hits.py, schemas/parquet_output_alerts.py, schemas/parquet_output_available_updates.py, schemas/parquet_output_cluster_info.py, schemas/parquet_output_conditional_update_conditions.py, schemas/parquet_output_conditional_update_risks.py, schemas/parquet_output_gatherers_info.py, schemas/parquet_output_operator_condition.py, schemas/parquet_output_rule_hits.py, schemas/parquet_output_workload_containers.py, schemas/parquet_output_workload_image_layers.py, schemas/platform_upload_announce_messages.py
- explicit symbol import instead of "star" import
- it help linters to figure out all possible problems
- checked already by linters
=> Fixed imports in schema definitions

schemas/validators_test.py
- all symbols are imported explicitly
- fixed test names
- removed one duplicated test
=> Fixed imports in validator test

schemas/sqs_messages.py
Fix imports in SQS message validator
=> Fix imports in SQS message validator

.github/workflows/ruff.yml, pyproject.toml
=> Enable Ruff on CI

data/sqs_payloads.py, pyproject.toml, schemas/parquet_output_alerts_test.py, schemas/parquet_output_conditional_update_risks.py, schemas/parquet_output_gatherers_info_test.py, schemas/parquet_output_workload_containers_test.py, schemas/parquet_output_workload_image_layers_test.py, schemas/validators.py, setup.py, tools/run_pycodestyle.py
- Fixed issues found by doc linter
- Setup docstring checker for CI
=> Fix issues found by doc linter + setup docstring checker for CI

schemas/parquet_output_available_updates_test.py, schemas/parquet_output_cluster_info_test.py, schemas/parquet_output_conditional_update_conditions_tests.py, schemas/parquet_output_conditional_update_risks_test.py, schemas/validators.py
- Make sure the attribute type will be incorrect by changing its value
- NoQA declaration where it make sense
- Update linter settings
=> Fix E721 problems

schemas/common.py, schemas/validators.py, tools/gen_base64.py, tools/gen_blake2.py, tools/gen_md5_sum.py, tools/gen_sha1_sum.py, tools/gen_sha224_sum.py, tools/gen_sha256_sum.py, tools/gen_sha384_sum.py, tools/gen_sha3_224_sum.py, tools/gen_sha3_256_sum.py, tools/gen_sha3_384_sum.py, tools/gen_sha3_512_sum.py, tools/gen_sha512_sum.py, tools/gen_shake_128_sum.py, tools/gen_shake_256_sum.py, tools/gen_timestamps.py, tools/gen_timestamps_ms.py, tools/gen_uuid.py
We are fully Python > 3.6 compatible now!
=> Use f-strings everywhere

pyproject.toml, tools/gen_timestamps.py, tools/gen_timestamps_ms.py, tools/gen_uuid.py
=> Removed unused loop variables
